// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhYPsgxKOVK1zHn2Bv0SZ8dSeHSRE_w4',
    appId: '1:701850273720:web:1bc3410422f7e3b786f14d',
    messagingSenderId: '701850273720',
    projectId: 'burma-brands',
    authDomain: 'burma-brands.firebaseapp.com',
    storageBucket: 'burma-brands.firebasestorage.app',
    measurementId: 'G-2VSYXNQZDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdwdRL82rPQzrI6ni_kD8EtYbRzInRW4',
    appId: '1:701850273720:android:a009972615dbbe9386f14d',
    messagingSenderId: '701850273720',
    projectId: 'burma-brands',
    storageBucket: 'burma-brands.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQP2RImp5z0lLXEJDow4TR7DwEx2_mdE',
    appId: '1:701850273720:ios:16d9ffc8f271d03586f14d',
    messagingSenderId: '701850273720',
    projectId: 'burma-brands',
    storageBucket: 'burma-brands.firebasestorage.app',
    iosBundleId: 'com.burmabrands.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiQP2RImp5z0lLXEJDow4TR7DwEx2_mdE',
    appId: '1:701850273720:ios:f6b9c89f6e5ec7b386f14d',
    messagingSenderId: '701850273720',
    projectId: 'burma-brands',
    storageBucket: 'burma-brands.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMhYPsgxKOVK1zHn2Bv0SZ8dSeHSRE_w4',
    appId: '1:701850273720:web:5cbe9acb40bc116b86f14d',
    messagingSenderId: '701850273720',
    projectId: 'burma-brands',
    authDomain: 'burma-brands.firebaseapp.com',
    storageBucket: 'burma-brands.firebasestorage.app',
    measurementId: 'G-XLEYEGK8VZ',
  );
}
